-- USERS TABLE
CREATE TABLE users(
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100),
username VARCHAR(50) UNIQUE,
password VARCHAR(255)
);

-- POSTS TABLE
CREATE TABLE posts(
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT,
content TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COMMENTS TABLE
CREATE TABLE comments(
id INT AUTO_INCREMENT PRIMARY KEY,
post_id INT,
user_id INT,
comment TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- LIKES TABLE
CREATE TABLE likes(
id INT AUTO_INCREMENT PRIMARY KEY,
post_id INT,
user_id INT
);

-- FOLLOWERS TABLE
CREATE TABLE followers(
id INT AUTO_INCREMENT PRIMARY KEY,
follower_id INT,
following_id INT
);

INSERT INTO users VALUES (1,'Test User','test','123');
